version: '2'

services:
  piserver:
    image: blost/pi_server
    command: 'java -jar Pi_server.jar'
    ports:
      - 9090:9090
    environment:
      - constraint:node==swarm-master

  piclient:
    image: blost/pi_client
    command: 'java -jar Pi_client.jar piserver'
    tty: true
    environment:
      - constraint:node==swarm-agent-01
    depends_on:
      - piserver

  memcached:
    image: memcached
    environment:
      - constraint:node==swarm-agent-02
    depends_on:
      - piserver

